wip: uk-localization build fix.
kubernetes-i18n-ukrainian/website pull request #100
Opened 2020-02-06 20:55 UTC by butuzov

Нормалізуємо білд:

В данному PR буде мінімально допустимий набір файлів для створення білда сайту.  Метою PR не є локалізація або провадження локалізованих матеріалів, але створення працездатного білда.

WIP.

```bash
make docker-image
make docker-build
```

2020-02-07 12:08 UTC, MaxymVlasov commented
Схоже це частково дублікує #1

2020-02-09 16:51 UTC, butuzov commented
1) додані певні файли необхідні для зборки проекту (examples/).
2) перекладено "Cтаттю що таке кубернетес?"

нотатки 
- деякі ресурси (templates) не перекладено
- деякі ресурси виправлено (_index.html) (коментарі видалені в yaml заголовку)
- *можливо* - виправити Настін текст в параграфі "що таке кубер", наші переклади трошки різняться. @anastyakulyk можеш глянути (текст щодо 15 років досвіду Google)?

чекаю на ваші коментарі панове та панянки

2020-02-10 09:10 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +Ця сторінка представляє собою поверхневий огляд Kubernetes.
"Представляє собою" русизм, давайте краще являє собою. Слово "поверхневий" в мене асоціюється з чимось недбалим( Може загальний або стислий?

2020-02-10 09:28 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +Kubernetes це платформа з відкритим джерельним кодом для управління контейнеризованими робочим навантаженнями та супутніми службами. Її основні властивості - портабельність, розширюваність, успішне в
Kubernetes - це платформа з відкритим джерельним кодом для управління контейнеризованими робочими навантаженнями та супутніми службами (сервісами?). Може, замість "портабельності" - "міжплатформність"?

2020-02-10 09:29 UTC, butuzov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +Ця сторінка представляє собою поверхневий огляд Kubernetes.
1) слушно
2) ну це ж дослівно overview, стислий і загальний підійшли б але жодний з компонентів не розглядається - тому це не загально і навіть не стисло, це "поверхнево"? може "узагальнений"?

2020-02-10 09:37 UTC, butuzov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +Kubernetes це платформа з відкритим джерельним кодом для управління контейнеризованими робочим навантаженнями та супутніми службами. Її основні властивості - портабельність, розширюваність, успішне в
"портабельність" і в мне викликала питання як його краще...і його таки краще треба в глосарій.

але - міжплатформенність, це походу здатність чогось бути між платфомрами, кросплатформенність (калька з англійської) - це вже ближче, але це не портабельніть.
може кросплатформенність краще?

2020-02-10 09:40 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +Kubernetes це платформа з відкритим джерельним кодом для управління контейнеризованими робочим навантаженнями та супутніми службами. Її основні властивості - портабельність, розширюваність, успішне в
Так, давайте кросплатформність. Щодо написання стаття у вікі https://uk.wikipedia.org/wiki/%D0%91%D0%B0%D0%B3%D0%B0%D1%82%D0%BE%D0%BF%D0%BB%D0%B0%D1%82%D1%84%D0%BE%D1%80%D0%BC%D0%BD%D1%96%D1%81%D1%82%D1%8C

2020-02-10 09:48 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +Назва Kubernetes походить з грецької та несе значення - кеманич або пілот. Google відкрив доступ джерельних кодів проекту Kubernetes у 2014 році. Kubernetes побудовано використовуючи [фундацію п'ятна
Назва Kubernetes походить з грецької та означає керманич, або пілот. Google відкрив доступ до джерельних кодів проекту Kubernetes у 2014 році.

Kubernetes побудовано [на базі п'ятнадцятилітнього досвіду, що Google отримав, оперуючи масштабними робочим навантаженнями](https://ai.google/research/pubs/pub43438) у купі з найкращими у своєму класі ідеями та практиками, які може запропонувати спільнота.
Щодо цього речення - мені здається, не страшно, якщо переклад трохи відрізнятиметься.

2020-02-10 09:48 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +## Подорожуючи назад у часі.
Може, ретроспектива?

2020-02-10 09:49 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +Давайте повернемось назад у часі і дізнаємось завдяки чому Kubernetes став таким корисним.
Давайте повернемось назад у часі і дізнаємось, завдяки чому Kubernetes став таким корисним.

2020-02-10 09:50 UTC, butuzov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +## Подорожуючи назад у часі.
Going back in time? це дослівно і відображає первинний інтеншен.

2020-02-10 09:50 UTC, butuzov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +Давайте повернемось назад у часі і дізнаємось завдяки чому Kubernetes став таким корисним.
ок. + "та" за мість "і"

2020-02-10 09:53 UTC, butuzov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +Назва Kubernetes походить з грецької та несе значення - кеманич або пілот. Google відкрив доступ джерельних кодів проекту Kubernetes у 2014 році. Kubernetes побудовано використовуючи [фундацію п'ятна
ок;

2020-02-10 10:13 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +**Ера традиційного розгортання:** На початку, організації запускали застосунки на фізичних серверах. Не існує способу задати обмеження використання ресурсів у такий спосіб, що спричиняло проблему вид
Я би трохи перефразувала друге речення: "Оскільки в такий спосіб не було можливості задати обмеження використання ресурсів, це спричиняло проблеми виділення та розподілення ресурсів на фізичних серверах". Наприклад: якщо багато застосунків було запущено на фізичному сервері, могли траплятись випадки, коли один застосунок забирав собі найбільше ресурсів, внаслідок чого інші програми просто недопрацьовували.

2020-02-10 10:16 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +**Ера традиційного розгортання:** На початку, організації запускали застосунки на фізичних серверах. Не існує способу задати обмеження використання ресурсів у такий спосіб, що спричиняло проблему вид
Але таке рішення погано масштабувалось, оскільки ресурси були не повністю використані; на додачу, це було дорого, оскільки організаціям потрібно було опікуватись фізичними серверами.

2020-02-10 10:23 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +**Ера віртуалізованого розгортання:** Як рішення - була представлена віртуалізвація. Вона дозволяла запускати багаточисленні Віртуальні Машини (Virtual Machines або VMs) на одному фізичному серверном
Як рішення - була представлена віртуалізація. Вона дозволяла запускати численні віртуальні машини (Virtual Machines або VMs) на одному фізичному серверному ЦПУ. Віртуалізація дозволила застосункам бути ізольованими у межах віртуальних машин та забезпечувала безпеку, оскільки інформація застосунку на одній VM не була доступна застосунку на іншій VM.

2020-02-10 10:27 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +**Ера віртуалізованого розгортання:** Як рішення - була представлена віртуалізвація. Вона дозволяла запускати багаточисленні Віртуальні Машини (Virtual Machines або VMs) на одному фізичному серверном
я би писала віртуальні машини з маленької. Вони всі сутності кубера возвеличують до великої літери, але як на мене, то зайве

2020-02-10 10:44 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +Віртуалізація дозволяла кращу утилізацію ресурсів на фізичному сервері на додачу до кращої масштабованості, тому що застосунок міг бути доданий або оновлений набагато легше, що зменшувало вартість на
Віртуалізація забезпечує краще використання ресурсів на фізичному сервері та кращу масштабованість, оскільки дозволяє легко додавати або оновлювати застосунки, зменшує витрати на фізичне обладнання, тощо. З віртуалізАцією ви можете...

2020-02-10 10:49 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +Кожна VM представляла собою повноцінну машину з усіма компонентами, включаючи операційну систему, поверх віртуалізаційного апаратного забезпечення.
Кожна VM є повноцінною машиною з усіма компонентами, включаючи операційну систему поверх віртуалізаційного апаратного забезпечення.

2020-02-10 10:58 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +**Ера розгортання контейнерів:** Контейнери схожі на VM, але мають спрощені характеристики ізольованості і розділяють операційну систему з усіма застосунками. Саму тому контейнери вважались легковісн
Контейнери подібні до VM, але... Саму тому контейнери вважаються легковісними. Подібно до VM, контейнер має власну файлову систему, ЦПУ, пам'ять, простір процесів, тощо.

2020-02-10 10:59 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +**Ера розгортання контейнерів:** Контейнери схожі на VM, але мають спрощені характеристики ізольованості і розділяють операційну систему з усіма застосунками. Саму тому контейнери вважались легковісн
Оскільки контейнери вивільнені від підпорядкованої інфраструктури, їх можна легко переміщати між хмарними провайдерами або дистрибутивами операційних систем.

2020-02-10 11:00 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +Контейнери стали популярнішими тому що пропонували додаткові переваги, такі як:
Контейнери стали популярними, тому що пропонували додаткові переваги, такі як:

2020-02-10 11:17 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +* Розподіл сумнівів розробки та операцій: створення образів контейнерів застосунків під час побудови/релізу на противагу часу розгортання, і як наслідок, вивільнення застосунків із інфраструктури.
```suggestion
* Розподіл відповідальності команд розробки та експлуатації: створення образів контейнерів застосунків під час побудови/релізу на противагу часу розгортання, і як наслідок, вивільнення застосунків із інфраструктури.
```

2020-02-10 11:21 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +* Спостереження не тільки за інформацією та метриками рівня операційної системи, а такою станом застосунку та іншими сигналами.
```suggestion
* Спостереження не лише за інформацією та метриками на рівні операційної системи, але й за станом застосунку та іншими сигналами.
```

2020-02-10 11:25 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +* Однорідність середовища для розробників, тестів та робочого навантаження: запускаємо те саме на вашому робочому комп'ютері, що і у хмарного провайдера.
```suggestion
* Однорідність середовища для розробки, тестування та робочого навантаження: запускається так само як на робочому комп'ютері, так і у хмарного провайдера.
```

2020-02-10 11:28 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +* Хмарна та Операційно-Системна переносимість: запускається на  Ubuntu, RHEL, CoreOS, у власному дата центрі, Google Kubernetes Engine, і взагалі будь де.
```suggestion
* Хмарна та операційно-системна кросплатформність: запускається на Ubuntu, RHEL, CoreOS, у власному дата-центрі, у Google Kubernetes Engine, і взагалі будь-де.
```

2020-02-10 11:31 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +* Application-centric management: Raises the level of abstraction from running an OS on virtual hardware to running an application on an OS using logical resources.
помилково оригінальний текст у перекладі

2020-02-10 11:34 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +* Застосунко-центроване керування: підвищення рівня абстрації від запуску операційної системи у віртуальному апаратному забезпеченні до запуску застосунка в операціні системі використовуючи логічні р
```suggestion
* Орієнтоване на застосунки керування: підвищення рівня абстрації від запуску операційної системи у віртуальному апаратному забезпеченні до запуску застосунку в операційній системі, використовуючи логічні ресурси.
```

2020-02-10 11:51 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +* Нещільно поєднані, розподілені, еластичні, звільнені мікро-сервіси: застосунки розбиваються у менші, незалежні частини що можуть бути розгорнутими та скерованими динамічно - не як монолітна побудов
```suggestion
* Нещільно зв'язані, розподілені, еластичні, вивільнені мікросервіси: застосунки розбиваються на менші, незалежні частини для динамічного розгортання та управління, на відміну від монолітної архітектури, що працює на одній великій виділеній машині.
```

2020-02-10 11:54 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +* Ізоляція ресурсів: передбачувана якість роботи застосунків.
```suggestion
* Ізоляція ресурсів: передбачувана продуктивність застосунку.
```

2020-02-10 12:16 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +## Чому вам потрібен Kebernetes та що він може робити
```suggestion
## Чому вам потрібен Kebernetes і що він може робити
```

2020-02-10 12:33 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +Контейнери прекрасний спосіб створення та запуску ваших застосунків. В робочому оточенні, вам потрібно керувати контейнерами (в яких працюють застосунки) та впевнюватись що не буде жодного простою. Н
```suggestion
Контейнери - це прекрасний спосіб упакувати та запустити ваші застосунки. У продуктивному оточенні вам потрібно керувати контейнерами, в яких працюють застосунки, і стежити, щоб не було простою. Наприклад, якщо один контейнер припиняє роботу, інший має бути запущений йому на заміну. Чи не легше зробити так, щоб цією поведінкою керувала сама система?
```

2020-02-10 12:48 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +Ось тут то Kuberntes приходе на допомогу! Kubernetes надає нам основу робочих інструментів для запуску еластичних розподілених систем. Він бере на себе обов'язки опіки за масштабуванням та аварійним
```suggestion
Ось де Kubernetes приходить на допомогу! Kubernetes надає вам каркас для еластичного запуску розподілених систем. Він опікується масштабуванням та аварійним відновленням вашого застосунку, пропонує шаблони розгортань, тощо. Наприклад, Kubernetes дозволяє легко створювати розгортання за стратегією canary у вашій системі.
```

2020-02-10 12:56 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +* **Визначення сервісів та балансування навантаження**
```suggestion
* **Виявлення сервісів та балансування навантаження**
```

2020-02-10 13:08 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +Kubernetes може надавати доступ до контейнера використовуючи DNS ім'я або його власну IP адресу. Якщо мережеве навантаження до контейнера завелике, Kubernetes здатний збалансувати та розподілити його
```suggestion
Kubernetes може надавати доступ до контейнера, використовуючи DNS-ім'я або його власну IP-адресу. Якщо контейнер зазнає завеликого мережевого навантаження, Kubernetes здатний збалансувати та розподілити його таким чином, щоб розгортання залишалось стабільним.
```

2020-02-10 13:16 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +Kubernetes дозволяє вам автоматично монтувати системи збереження інформації на ваш вибір: локальні сховища, пропозиції хмарних провайдерів, тощо.
```suggestion
Kubernetes дозволяє вам автоматично монтувати системи збереження інформації на ваш вибір: локальні сховища, пропозиції від хмарних провайдерів, тощо.
```

2020-02-10 13:20 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +* **Автоматичні оновлення та відкатування**
```suggestion
* **Автоматичне розгортання та відкат**
```

2020-02-10 13:45 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +Використовуючи Kubernetes ви можете описати бажаний стан контейнерів що розгортаються, і він прослідкує за досягненням цього стану в контрольованій манері. Наприклад, ви можете автоматизувати Kuberne
```suggestion
Використовуючи Kubernetes, ви можете описати бажаний стан контейнерів, що розгортаються, і він регульовано змінюватиме поточний стан, доки він не дорівнюватиме бажаному. Наприклад, ви можете автоматизувати в Kubernetes процеси створення нових контейнерів для розгортання, видалення існуючих контейнерів і передачу їхніх ресурсів на новостворені контейнери.
```

2020-02-10 13:59 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +* **Автоматичне розміщення завдань**
```suggestion
* **Автоматичне розміщення задач**
```

2020-02-10 14:06 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +Ви задовольняєте потребу Kubernetes у кластері робочих машин (нод), що будуть використані для запуску контейнерних завдань, і вказавши скільки ЦПУ та пам'яті необхідно кожному контейнеру Kuberentes р
```suggestion
Ви надаєте Kubernetes кластер робочих машин (вузлів) для запуску контейнерізованих задач і вказуєте, скільки ЦПУ та пам'яті необхідно для кожного контейнера. Kubernetes розподілить контейнери по вузлах таким чином, щоб використання ресурсів було оптимальним.
```

2020-02-10 14:06 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +Ви задовольняєте потребу Kubernetes у кластері робочих машин (нод), що будуть використані для запуску контейнерних завдань, і вказавши скільки ЦПУ та пам'яті необхідно кожному контейнеру Kuberentes р
Я пропоную "нода" перекладати як вузол.

2020-02-10 14:08 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +* **Самозцілення**
Може, самовідновлення?

2020-02-10 14:12 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +Kubernetes перезавантажить контейнер що дає збої, замінить контейнери, припинить роботу таких що не відповідають на визначені користувачем перевірки стану, і не буде оголошувати їх наявність системі
```suggestion
Kubernetes перезапускає контейнери, що відмовили; заміняє контейнери; зупиняє роботу контейнерів, що не відповідають на задану користувачем перевірку стану, і не повідомляє про них клієнтам, допоки ці контейнери не будуть у стані робочої готовності. 
```

2020-02-10 14:23 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +Kubernetes дозволяє вам зберігати та керувати чутливою інформацією, такою як: паролі, OAuth токени та SSH ключі. Ви можете публікувати або оновлювати секрети та конфігурацю без перебудови образів ваш
```suggestion
Kubernetes дозволяє вам зберігати та керувати чутливою інформацією, такою як паролі, OAuth токени та SSH ключі. Ви можете розгортати та оновлювати секрети та конфігурацю без перебудови образів ваших контейнерів, не розкриваючи секрети в конфігурацію стека. 
```

2020-02-10 14:54 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +Kubernetes не є традиційною, системою PaaS все-включено (Платформа як послуга). Kubernetes оперує скорше на рівні контейнерів, ніж на рівні апаратного забезпечення, деякі особливості платформи якими
```suggestion
Kubernetes не є комплексною системою PaaS (Платформа як послуга) у традиційному розумінні. Оскільки Kubernetes оперує швидше на рівні контейнерів, аніж на рівні апаратного забезпечення, деяка загальнозастосована функціональність і справді є спільною з PaaS, як-от розгортання, масштабування, розподіл навантаження, логування і моніторинг. Водночас Kubernetes не є монолітним, а вищезазначені особливості підключаються і є опціонними. Kubernetes надає будівельні блоки для створення платформ для розробки, але залишає за користувачем право вибору у важливих питаннях.
```

2020-02-10 15:10 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +* Не обмежує типи застосунків що підтримуються. Kuberntes намагається підтримувати екстримально різноманітні типи навантажень, включаючи такі яким потрібне зберігання стану так і такі яким воно непот
```suggestion
* Не обмежує типи застосунків, що підтримуються. Kubernetes має на меті підтримку широкого розмаїття  робочих навантажень, як без збереження поточного стану (stateless), так і зі збереженням (stateful), навантажень по обробці даних, тощо. Якщо застосунок можна запустити в контейнері, він чудово працюватиме під управлінням Kubernetes.
```

2020-02-10 15:17 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +* Не розгортає застосунки з джерельних кодів та не будує ваші застосунки. Процеси безперервної інтеграції, доставка та розгортання (так звані CI/CD інструменти) визначаються на рівні організації, та
```suggestion
* Не розгортає застосунки з вихідного коду та не збирає ваші застосунки. Процеси безперервної інтеграції, доставки та розгортання (так звані CI/CD інструменти) визначаються на рівні організації, виходячи з технічних вимог.
```

2020-02-10 15:33 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +* Не надає служби на рівні застосунків - такі як програми-посередники (наприклад, тонелі повідомлень), фреймворки обробки даних (наприклад Spark), бази даних (наприклад MYSQL), кеші, не кластерні сис
```suggestion
* Не надає сервіси на рівні застосунків як вбудовані: програмне забезпечення проміжного рівня (наприклад, шина передачі повідомлень), фреймворки обробки даних (наприклад, Spark), бази даних (наприклад, MySQL), кеш, некластерні системи збереження інформації (наприклад, Ceph). Ці компоненти можуть бути запущені у Kubernetes та/або бути доступними для застосунків за допомогою спеціальних механізмів, наприклад [Open Service Broker](https://openservicebrokerapi.org/).
```

2020-02-10 15:41 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +* Не змушує використовувати рішення для протоколювання, моніторингу та сповіщень, натомість дозволяє використовувати деякі інтеграції як доказ що це можливо, та механізми по збору та експорту метрик.
```suggestion
* Не нав'язує використання інструментів для логування, моніторингу та сповіщень, натомість надає певні інтеграційні рішення як прототипи, та механізми зі збирання та експорту метрик.
```

2020-02-10 15:45 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +* Не надає та не змушує використовувати якусь конфігураційну мову/систему (як наприклад `Jsonnet`), натомість надає можливість використовувати API що може бути використаний довільними формами деклара
```suggestion
* Не надає та не змушує використовувати певну конфігураційну мову/систему (як наприклад `Jsonnet`), натомість надає можливість використовувати API, що може бути використаний довільними формами декларативних специфікацій.
```

2020-02-10 15:52 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +* Не надає і не планує вбудовувати будь-яку систему машинної конфігурації, обслуговування, управління або самозцілення.
```suggestion
* Не надає і не запроваджує жодних систем машинної конфігурації, підтримки, управління або самовідновлення.
```

2020-02-10 16:10 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +* На додачу, Kubernetes не просто система оркестрації. Насправді, вона прибирає потребу оркестрації як такої. Технічне визначення оркестрації - це запуск визначених процесів: спочатку A, за ним B, по
```suggestion
* На додачу, Kubernetes - це не просто система оркестрації. Власне кажучи, вона усуває потребу оркестрації як такої. Якщо звернутися до технічного визначення, оркестрація - це запуск визначених процесів: спочатку A, за ним B, потім C. Натомість Kubernetes складається з певної множини незалежних, складних процесів управління, що безперервно змінюють поточний стан у напрямку бажаного, що заданий у конфігурації. Неважливо, як ви дістанетесь з пункту A до пункту C. Централізоване управління також не є обов'язковим. Все це виливається в систему, якою легше користуватися, і яка є більш потужною, надійною, стійкою та здатною до легкого розширення.
```

2020-02-10 16:45 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +Kubernetes це платформа з відкритим джерельним кодом для управління контейнеризованими робочим навантаженнями та супутніми службами. Її основні властивості - портабельність, розширюваність, успішне в
```suggestion
Kubernetes - це платформа з відкритим вихідним кодом для управління контейнеризованими робочими навантаженнями та супутніми службами.
```
Перепрошую, що повторно. З'ясувала, що слово "джерельний" вживається лише у прямому, водному контексті

2020-02-10 16:46 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +Назва Kubernetes походить з грецької та несе значення - кеманич або пілот. Google відкрив доступ джерельних кодів проекту Kubernetes у 2014 році. Kubernetes побудовано використовуючи [фундацію п'ятна
... доступ до вихідних кодів...

2020-02-10 18:11 UTC, butuzov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +Kubernetes це платформа з відкритим джерельним кодом для управління контейнеризованими робочим навантаженнями та супутніми службами. Її основні властивості - портабельність, розширюваність, успішне в
ок. я вношу частину змін. окрім видаленні речення про характеристики і джерельних кодів.

2020-02-10 18:21 UTC, butuzov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +* Не надає і не планує вбудовувати будь-яку систему машинної конфігурації, обслуговування, управління або самозцілення.
Частково змінюю. Self-healing - це самозцілення, self-restoring це самовідновлення, maintenance завжди було обслуговуванням.

2020-02-10 18:25 UTC, butuzov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +* Не надає та не змушує використовувати якусь конфігураційну мову/систему (як наприклад `Jsonnet`), натомість надає можливість використовувати API що може бути використаний довільними формами деклара
ОК. Плюс прибрав може/можливість як тафталогію.

2020-02-10 18:30 UTC, butuzov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +* Не змушує використовувати рішення для протоколювання, моніторингу та сповіщень, натомість дозволяє використовувати деякі інтеграції як доказ що це можливо, та механізми по збору та експорту метрик.
* логування то калька з англійської, **log** то журнал або протокол, тут або журналювання або протоколювання. 
* "proof of concept" -> прототип? впевнена?
* @MaxymVlasov твоя думка щодо "по збору та експорту метрик" чи "зі збирання та експорту метрик"?

2020-02-10 18:38 UTC, butuzov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +* Не розгортає застосунки з джерельних кодів та не будує ваші застосунки. Процеси безперервної інтеграції, доставка та розгортання (так звані CI/CD інструменти) визначаються на рівні організації, та
ok

2020-02-10 18:40 UTC, butuzov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +* Не обмежує типи застосунків що підтримуються. Kuberntes намагається підтримувати екстримально різноманітні типи навантажень, включаючи такі яким потрібне зберігання стану так і такі яким воно непот
ok

2020-02-10 18:41 UTC, butuzov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +Kubernetes не є традиційною, системою PaaS все-включено (Платформа як послуга). Kubernetes оперує скорше на рівні контейнерів, ніж на рівні апаратного забезпечення, деякі особливості платформи якими
ok

2020-02-10 18:43 UTC, butuzov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +Kubernetes дозволяє вам зберігати та керувати чутливою інформацією, такою як: паролі, OAuth токени та SSH ключі. Ви можете публікувати або оновлювати секрети та конфігурацю без перебудови образів ваш
ok

2020-02-10 18:44 UTC, butuzov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +* **Самозцілення**
Треба арбітра. Я за "самозцілення". 
@MaxymVlasov

2020-02-10 18:49 UTC, butuzov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +Віртуалізація дозволяла кращу утилізацію ресурсів на фізичному сервері на додачу до кращої масштабованості, тому що застосунок міг бути доданий або оновлений набагато легше, що зменшувало вартість на
ок слушно.

2020-02-10 18:50 UTC, butuzov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +**Ера віртуалізованого розгортання:** Як рішення - була представлена віртуалізвація. Вона дозволяла запускати багаточисленні Віртуальні Машини (Virtual Machines або VMs) на одному фізичному серверном
ок

2020-02-10 19:01 UTC, butuzov commented
дякую за гарне ревю, я від ніього не скоро відійду! =)

2020-02-11 00:57 UTC, MaxymVlasov requested changes
Я пас'ятаю що PR був не по локалізації,  однак)
Може @anastyakulyk виправить. До того ж, я там по гломапію понакидував. 
Насть, збери, будь ласка, це добро кудись і постав по емоджі під коментарями про гломарій - щоб розуміти що тред можна без резолвити

2020-02-11 00:57 UTC, MaxymVlasov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +## Подорожуючи назад у часі.
Ще як варіант: Озираючись на першопричини

Дослівно воно трохи по дерев'яному  звучить

2020-02-11 00:57 UTC, MaxymVlasov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +**Ера традиційного розгортання:** На початку, організації запускали застосунки на фізичних серверах. Оскільки в такий спосіб не було можливості задати обмеження використання ресурсів, це спричиняло п
```suggestion
**Ера традиційного розгортання:** На початку, організації запускали застосунки на фізичних серверах. Оскільки в такий спосіб не було можливості задати обмеження використання ресурсів, це спричиняло проблеми виділення та розподілення ресурсів на фізичних серверах. Наприклад: якщо багато застосунків було запущено на фізичному сервері, могли траплятись випадки, коли один застосунок забирав собі найбільше ресурсів, внаслідок чого інші програми просто недопрацьовували. Рішенням може бути запуск кожного застосунку на окремому фізичному сервері. Але такий підхід погано масштабується, оскільки ресурси не повністю використовуються; на додачу, це дорого, оскільки організаціям потрібно було опікуватись фізичними серверами.
```

2020-02-11 00:57 UTC, MaxymVlasov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +**Ера віртуалізованого розгортання:** Як рішення - була представлена віртуалізація. Вона дозволяла запускати численні віртуальні машини (Virtual Machines або VMs) на одному фізичному серверному ЦПУ.
```suggestion
**Ера віртуалізованого розгортання:** Як рішення - була представлена віртуалізація. Вона дозволяє запускати численні віртуальні машини (Virtual Machines або VMs) на одному фізичному ЦПУ сервера. Віртуалізація дозволила застосункам бути ізольованими у межах віртуальних машин та забезпечувала безпеку, оскільки інформація застосунку на одній VM не була доступна застосунку на іншій VM.
```

2020-02-11 00:57 UTC, MaxymVlasov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +Віртуалізація забезпечує краще використання ресурсів на фізичному сервері та кращу масштабованість, оскільки дозволяє легко додавати або оновлювати застосунки, зменшує витрати на фізичне обладнання,
```suggestion
Віртуалізація забезпечує краще використання ресурсів на фізичному сервері та кращу масштабованість, оскільки дозволяє легко додавати та оновлювати застосунки, зменшує витрати на фізичне обладнання тощо. З віртуалізацією ви можете представити ресурси у вигляді одноразових віртуальних машин.
```

2020-02-11 00:57 UTC, MaxymVlasov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +Кожна VM є повноцінною машиною з усіма компонентами, включаючи операційну систему поверх віртуалізаційного апаратного забезпечення.
```suggestion
Кожна VM є повноцінною машиною з усіма компонентами, включно з власною операційною системою, запущені поверх віртуалізованого апаратного забезпечення.
```

2020-02-11 00:57 UTC, MaxymVlasov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +Кожна VM є повноцінною машиною з усіма компонентами, включаючи операційну систему поверх віртуалізаційного апаратного забезпечення.
І да - VM - теж в глосарій
Можна перекладати як ВМ - досить поширене скорочення у тех.літературі

2020-02-11 00:57 UTC, MaxymVlasov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +**Ера розгортання контейнерів:** Контейнери схожі на VM, але мають спрощені характеристики ізольованості і розділяють операційну систему з усіма застосунками. ССаму тому контейнери вважаються легкові
```suggestion
**Ера розгортання контейнерів:** Контейнери схожі на VM, але мають спрощений варіант ізольованості і використовують спільну операційну систему для усіх застосунків. Саму тому контейнери вважаються легковісними. Подібно до VM, контейнер має власну файлову систему, ЦПУ, пам'ять, простір процесів тощо. Оскільки контейнери вивільнені від підпорядкованої інфраструктури, їх можна легко переміщати між хмарними провайдерами чи дистрибутивами операційних систем.
```

2020-02-11 00:57 UTC, MaxymVlasov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +**Ера розгортання контейнерів:** Контейнери схожі на VM, але мають спрощені характеристики ізольованості і розділяють операційну систему з усіма застосунками. ССаму тому контейнери вважаються легкові
`clouds - хмарні провайдери` - в глосарій

2020-02-11 00:57 UTC, MaxymVlasov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +* Безперервна розробка, інтеграція та розгортання: забезпечення надійних та безперервних побудов контейнерів та їх швидке розгортання та легкі відкатування (за рахунок незмінності образів).
Continuous development, integration, and deployment: - теж в глосарій, от з тим перекладом що тут

2020-02-11 00:57 UTC, MaxymVlasov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +* Безперервна розробка, інтеграція та розгортання: забезпечення надійних та безперервних побудов контейнерів та їх швидке розгортання та легкі відкатування (за рахунок незмінності образів).
Декілька "та" - по ідеї десь має бути кома

2020-02-11 00:57 UTC, MaxymVlasov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +* Безперервна розробка, інтеграція та розгортання: забезпечення надійних та безперервних побудов контейнерів та їх швидке розгортання та легкі відкатування (за рахунок незмінності образів).
`image - образ`?
Глосарій

2020-02-11 00:57 UTC, MaxymVlasov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +* Розподіл відповідальності команд розробки та експлуатації: створення образів контейнерів застосунків під час побудови/релізу на противагу часу розгортання, і як наслідок, вивільнення застосунків із
Перечитав що переклад що оригінал - зрозумів що мав га уаазі автор, та щось занадто складено. Може перефразувати якось? Студент 3-4-го курсу не зрозуміє

2020-02-11 00:57 UTC, MaxymVlasov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +* Спостереження не лише за інформацією та метриками на рівні операційної системи, але й за станом застосунку та іншими сигналами.
Реквестую перепис ~населення~. Мб від Насті.

В мене враження що по дорозі загубили важливу частину змісту

Далі поки не ревьювив

2020-02-11 01:02 UTC, MaxymVlasov commented on content/ru/case-studies/_index.html
> +---
І це релагування RU файлу? Ой. 
Треба в правила ревью поруч з глосарієм вписати перевірку в яких теках змііни зроблені

2020-02-11 05:58 UTC, butuzov commented on content/ru/case-studies/_index.html
> +---
лінію не ставляє у мене лише для [md](https://github.com/butuzov/dots/blob/master/.editorconfig) чому тут прибрало...  російську випадкво зачепило, я створю новий PR основуючись на змінах до яких фінально прийдемо.

2020-02-11 06:22 UTC, butuzov commented on content/uk/_common-resources/index.md
> +---
Я вніс зміни в свою конфігурацію - тобто надалі вставлятиме нову лінію, але jic в markdown зазвичай (ну я точно не бачив багато прикладів) не потребують фінальну лінію, там у них свій сет дурнуватих правил.

2020-02-11 06:57 UTC, butuzov commented on content/uk/docs/concepts/overview/_index.md
> +---
```
find . -name "*.md" |  xargs -I {} sh -c "./test2.py {}" | sort | uniq -c | sort -nr
2681 NEW_LINE
 199 NO_NEW_LINE
   2 NO_DATA
```
ой. тут таких як я 7 відсотків.

2020-02-11 09:02 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +* Не змушує використовувати рішення для протоколювання, моніторингу та сповіщень, натомість дозволяє використовувати деякі інтеграції як доказ що це можливо, та механізми по збору та експорту метрик.
- я за переклад logging як логування
- "proof of concept"  переклад: https://www.multitran.com/m.exe?l1=1&l2=2&s=proof-of-concept

2020-02-11 09:04 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +* Не надає і не планує вбудовувати будь-яку систему машинної конфігурації, обслуговування, управління або самозцілення.
Ок) нам завжди наголошували, що переклад - це справа творча)

2020-02-11 09:18 UTC, anastyakulyk commented on content/uk/case-studies/_index.html
> +abstract: Підбріка користувачів що викоирстовують Kubernetes для робочих навантажень.
Підбріка користувачів, що викоирстовують Kubernetes для робочих навантажень.

2020-02-11 09:24 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +* Безперервна розробка, інтеграція та розгортання: забезпечення надійних та безперервних побудов контейнерів та їх швидке розгортання та легкі відкатування (за рахунок незмінності образів).
Точно. Пропоную так: Безперервна розробка, інтеграція та розгортання: забезпечення надійних та безперервних побудов контейнерів, їх швидке розгортання та легкі відкатування (за рахунок незмінності образів).

2020-02-11 13:16 UTC, MaxymVlasov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +* Не змушує використовувати рішення для протоколювання, моніторингу та сповіщень, натомість дозволяє використовувати деякі інтеграції як доказ що це можливо, та механізми по збору та експорту метрик.
У журналювання є своє значення, яке не завжди пересікається з логуванням
Для прикладу: https://en.wikipedia.org/wiki/Journaling_file_system

Також ми можемо знайти використання слів "лог" і "журнал" як синоніми в англійській мові - https://en.wikipedia.org/wiki/Transaction_log. Тому я б не важав це калькою. Варто розрізняти запозичення і кальки.

Щодо "протоколювання" - не впевнений що це слово взагалі десь використовується відносно логів. І було б логічно, раз ми вже використовуємо слово "логи" а не "журнали програм" чи "протоколи програм" (цікаво що без додавання слова "програм" - буде складно зрозуміти про що мова)

2020-02-11 14:09 UTC, MaxymVlasov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +* Не надає і не планує вбудовувати будь-яку систему машинної конфігурації, обслуговування, управління або самозцілення.
@anastyakulyk і це в глосарій пліз

2020-02-11 14:09 UTC, MaxymVlasov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +* Не надає і не планує вбудовувати будь-яку систему машинної конфігурації, обслуговування, управління або самозцілення.
Всі 3 терміна

2020-02-11 14:18 UTC, anastyakulyk commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +* Не надає і не планує вбудовувати будь-яку систему машинної конфігурації, обслуговування, управління або самозцілення.
ок

2020-02-11 15:26 UTC, butuzov commented
Я зараз пройдусь по зауваженнях, що можу буду виправляти та пушити окремим коммітом.

2020-02-11 15:33 UTC, butuzov commented on content/uk/case-studies/_index.html
> +abstract: Підбріка користувачів що викоирстовують Kubernetes для робочих навантажень.
виправив.

2020-02-11 15:34 UTC, butuzov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +## Подорожуючи назад у часі.
ок. ставою **Озираючись на першопричини**

2020-02-11 15:37 UTC, butuzov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +* Не змушує використовувати рішення для протоколювання, моніторингу та сповіщень, натомість дозволяє використовувати деякі інтеграції як доказ що це можливо, та механізми по збору та експорту метрик.
додав "логування" та "прототипи"

2020-02-11 15:39 UTC, butuzov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +Кожна VM є повноцінною машиною з усіма компонентами, включаючи операційну систему поверх віртуалізаційного апаратного забезпечення.
додав.

2020-02-11 15:41 UTC, butuzov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +* Безперервна розробка, інтеграція та розгортання: забезпечення надійних та безперервних побудов контейнерів та їх швидке розгортання та легкі відкатування (за рахунок незмінності образів).
змінив.

2020-02-11 15:44 UTC, butuzov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +* Розподіл відповідальності команд розробки та експлуатації: створення образів контейнерів застосунків під час побудови/релізу на противагу часу розгортання, і як наслідок, вивільнення застосунків із
змінив перший пункт:
> Створення та розгортання застосунків за методологією Agile: спрощення та більш ефективне створення образів контейнерів у порівнянні до використання образів віртуальних машин.

2 та 3 вже змінено за настанової Насті.

2020-02-11 15:47 UTC, butuzov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +Kubernetes - це платформа з відкритим джерельним кодом для управління контейнеризованими робочими навантаженнями та супутніми службами. Її основні характеристики - кросплатформенність, розширюваність
зробив три заміни у тесті. мабуть варто додати до глосарію?

2020-02-11 15:56 UTC, butuzov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +Віртуалізація забезпечує краще використання ресурсів на фізичному сервері та кращу масштабованість, оскільки дозволяє легко додавати або оновлювати застосунки, зменшує витрати на фізичне обладнання,
змінив.

2020-02-11 15:58 UTC, butuzov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +**Ера віртуалізованого розгортання:** Як рішення - була представлена віртуалізація. Вона дозволяла запускати численні віртуальні машини (Virtual Machines або VMs) на одному фізичному серверному ЦПУ.
змінив.

2020-02-11 16:17 UTC, butuzov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +Кожна VM є повноцінною машиною з усіма компонентами, включаючи операційну систему поверх віртуалізаційного апаратного забезпечення.
вніз зміни

2020-02-11 16:19 UTC, butuzov commented on content/ru/case-studies/_index.html
> +---
Максе, перевір власні налаштування. `.editorconfig` проекту залишає вибір за користувачем чи вставляти "\n", у мене автоатично підхопило вимогу, твій .editorconfig походу ні.

2020-02-13 12:10 UTC, MaxymVlasov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +* **Самозцілення**
Самозцілення краще передає посил.
Дослівно - Самолікування ~може бути шкідливе для вашого здоров'я~

2020-02-15 17:28 UTC, butuzov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +## Чим Kubernetes не є
ok

2020-02-15 17:31 UTC, butuzov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +Kubernetes дозволяє вам автоматично монтувати системи збереження інформації на ваш вибір: локальні сховища, пропозиції від хмарних провайдерів, тощо.
offering як рішення? імхо це все ж "пропозиція", те що тобі пропонують купити. рішення в данному контексті можу бути опенсорсом яким. якщо все ж наполягаєш я зміню цей рядок, але імхо не воно.

2020-02-15 17:32 UTC, butuzov commented on content/uk/docs/templates/feature-state-alpha.txt
> +
наразі не треба. можна підніше відразу орієнтуючись на те де цей темплейт буде використано (там воно від використаних шорткодів залежить). я б зараз лишив... але відредагував при першій нагоді.

2020-02-15 17:53 UTC, butuzov commented on content/uk/docs/templates/feature-state-stable.txt
> +* Stable versions of features will appear in released software for many subsequent versions.
давай темплейти перекладу в наступному батчі а не в цьому?

2020-02-16 14:20 UTC, MaxymVlasov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +Kubernetes дозволяє вам автоматично монтувати системи збереження інформації на ваш вибір: локальні сховища, пропозиції від хмарних провайдерів, тощо.
В оригіналі нема ні слова про `offering`. Опенсорс != безкоштовне.
Рішення - це імплементація чогось.
Пропозиція - це пропонування зробити щось.

```
Kubernetes allows you to automatically mount a storage system of your choice, such as local storages, public cloud providers, and more.
```

2020-02-16 14:22 UTC, MaxymVlasov commented on content/uk/docs/templates/feature-state-stable.txt
> +* Stable versions of features will appear in released software for many subsequent versions.
Ок, давай

2020-02-16 14:53 UTC, butuzov commented on content/uk/docs/concepts/overview/what-is-kubernetes.md
> +Kubernetes дозволяє вам автоматично монтувати системи збереження інформації на ваш вибір: локальні сховища, пропозиції від хмарних провайдерів, тощо.
Гарно помічено! Не розумію де я під час перекладу "cloud providers offerings" помітив.

2020-02-16 15:13 UTC, butuzov commented
Чи є у когось ще зауваження чи можемо переходити до зливання wtfk8s ?

2020-02-17 09:00 UTC, anastyakulyk commented
Як на мене, все ок

2020-02-18 06:15 UTC, butuzov commented
закрито на користь #102

2020-02-18 06:15 UTC, closed without merging